const { RichEmbed } = require('discord.js');

module.exports = {
    name: 'ban',
    description: 'Ban member from the discord server',

    cooldown: 5,

    /*! Protection from DM */
    guildOnly: true,

    execute(message, args) {
        if(!message.mentions.users.size)
            return message.reply('You need to tag an user in order to ban them');

        if(message.member.hasPermission('BAN_MEMBERS')) {
            const taggedUser = message.mentions.users.first();

            if(args.length < 2)
                message.channel.send('The correct usage is: !ban @user reason');
            else {
                const reason = args.slice(1).join(' ');

                const banMessage = new RichEmbed()
                    .setColor('0xFF0000')
                    .setTitle('Banhammer')
                    
                    .setAuthor(`${message.member.user.username}`, `${message.member.user.displayAvatarURL}`)
                    .setDescription(`The reason that the user is going to be banned for is ${reason}`)
                    
                    .addBlankField()

                    .addField('Username', taggedUser.username, true)
                    .addField('Tag', taggedUser.tag, true)

                    .addField('Created at ', message.author.createdAt, true)
                    .addField('Last message', message.author.lastMessage, true)
                    
                    .setThumbnail(taggedUser.displayAvatarURL)

                    .setTimestamp()
                    .setFooter('Generated by AMXX-BG Bot');

                if(taggedUser) {
                    const member = message.guild.member(taggedUser);

                    if(member) {
                        message.channel.send(banMessage);
                        member.ban('You have been banned for ```' + reason + ' ``` ')
                    }
                }

            }
        } else
            message.channel.send('```You do not have permissions for this command!```');
    }
};